export interface GivingRecord {
  month: string;
  tithe: number;
  offering: number;
  special: number;
}

export interface ServiceRecord {
  label: string;
  attended: boolean;
}

export interface Milestone {
  type: "birthday" | "baptism" | "wedding" | "membership" | "salvation";
  label: string;
  date: string;
  upcoming: boolean;
  daysAway?: number;
}

export interface Note {
  id: string;
  author: string;
  date: string;
  content: string;
}

export interface Member {
  id: string;
  name: string;
  initials: string;
  avatarColor: string;
  phone: string;
  email: string;
  ministry: string;
  ministries: string[];
  joinDate: string;
  status: "Active" | "Inactive" | "First-timer";
  gender: "Male" | "Female";
  address: string;
  birthday: string;
  baptismDate: string;
  confirmationDate: string;
  salvationDate: string;
  spouse?: string;
  children: string[];
  totalGivingYTD: number;
  attendanceRate: number;
  eventsAttended: number;
  streak: number;
  givingHistory: GivingRecord[];
  serviceAttendance: ServiceRecord[];
  milestones: Milestone[];
  notes: Note[];
}

export const members: Member[] = [
  {
    id: "1",
    name: "Emmanuel Asante",
    initials: "EA",
    avatarColor: "#C8860A",
    phone: "+233 24 123 4567",
    email: "e.asante@email.com",
    ministry: "Choir",
    ministries: ["Choir", "Men's Fellowship"],
    joinDate: "Jan 15, 2020",
    status: "Active",
    gender: "Male",
    address: "12 Ashanti Road, Kumasi",
    birthday: "Jun 15, 1990",
    baptismDate: "Mar 20, 2021",
    confirmationDate: "Apr 10, 2022",
    salvationDate: "Feb 2, 2020",
    spouse: "Abena Asante",
    children: ["Kofi Asante", "Ama Asante"],
    totalGivingYTD: 8500,
    attendanceRate: 92,
    eventsAttended: 45,
    streak: 12,
    givingHistory: [
      { month: "Jan", tithe: 500, offering: 150, special: 0 },
      { month: "Feb", tithe: 500, offering: 200, special: 0 },
      { month: "Mar", tithe: 600, offering: 150, special: 100 },
      { month: "Apr", tithe: 500, offering: 180, special: 0 },
      { month: "May", tithe: 700, offering: 200, special: 200 },
      { month: "Jun", tithe: 500, offering: 220, special: 0 },
    ],
    serviceAttendance: [
      { label: "Jun 1", attended: true },
      { label: "May 25", attended: true },
      { label: "May 18", attended: true },
      { label: "May 11", attended: true },
      { label: "May 4", attended: false },
      { label: "Apr 27", attended: true },
      { label: "Apr 20", attended: true },
      { label: "Apr 13", attended: true },
      { label: "Apr 6", attended: true },
      { label: "Mar 30", attended: false },
      { label: "Mar 23", attended: true },
      { label: "Mar 16", attended: true },
    ],
    milestones: [
      { type: "birthday", label: "Birthday", date: "Jun 15, 2026", upcoming: true, daysAway: 11 },
      { type: "wedding", label: "Wedding Anniversary", date: "Sep 8, 2026", upcoming: true, daysAway: 96 },
      { type: "membership", label: "Member Anniversary", date: "Jan 15, 2027", upcoming: true, daysAway: 226 },
      { type: "baptism", label: "Baptism Anniversary", date: "Mar 20, 2026", upcoming: false },
    ],
    notes: [
      { id: "n1", author: "Pastor Emmanuel", date: "May 15, 2026", content: "Showing great leadership in the choir. Consider for assistant choir director role." },
      { id: "n2", author: "Admin", date: "Mar 2, 2026", content: "Requested prayer for family health situation. Follow up this month." },
    ],
  },
  {
    id: "2",
    name: "Abena Mensah",
    initials: "AM",
    avatarColor: "#2D1B69",
    phone: "+233 20 987 6543",
    email: "a.mensah@email.com",
    ministry: "Ushering",
    ministries: ["Ushering", "Women's Fellowship", "Prayer Team"],
    joinDate: "Mar 8, 2019",
    status: "Active",
    gender: "Female",
    address: "45 Liberation Road, Accra",
    birthday: "Aug 22, 1988",
    baptismDate: "Jun 5, 2019",
    confirmationDate: "Jul 15, 2020",
    salvationDate: "Mar 8, 2019",
    children: ["Kwame Mensah"],
    totalGivingYTD: 5200,
    attendanceRate: 88,
    eventsAttended: 38,
    streak: 8,
    givingHistory: [
      { month: "Jan", tithe: 300, offering: 100, special: 0 },
      { month: "Feb", tithe: 300, offering: 120, special: 50 },
      { month: "Mar", tithe: 400, offering: 100, special: 0 },
      { month: "Apr", tithe: 300, offering: 130, special: 0 },
      { month: "May", tithe: 350, offering: 150, special: 0 },
      { month: "Jun", tithe: 300, offering: 100, special: 0 },
    ],
    serviceAttendance: [
      { label: "Jun 1", attended: true },
      { label: "May 25", attended: true },
      { label: "May 18", attended: false },
      { label: "May 11", attended: true },
      { label: "May 4", attended: true },
      { label: "Apr 27", attended: true },
      { label: "Apr 20", attended: false },
      { label: "Apr 13", attended: true },
      { label: "Apr 6", attended: true },
      { label: "Mar 30", attended: true },
      { label: "Mar 23", attended: true },
      { label: "Mar 16", attended: false },
    ],
    milestones: [
      { type: "birthday", label: "Birthday", date: "Aug 22, 2026", upcoming: true, daysAway: 79 },
      { type: "baptism", label: "Baptism Anniversary", date: "Jun 5, 2026", upcoming: true, daysAway: 1 },
      { type: "membership", label: "Member Anniversary", date: "Mar 8, 2027", upcoming: true, daysAway: 277 },
    ],
    notes: [
      { id: "n3", author: "Pastor Emmanuel", date: "Apr 20, 2026", content: "Excellent ushering team leader. Nominated for deaconess role this quarter." },
    ],
  },
  {
    id: "3",
    name: "Kofi Boateng",
    initials: "KB",
    avatarColor: "#0A4A3A",
    phone: "+233 27 456 7890",
    email: "k.boateng@email.com",
    ministry: "Media & Tech",
    ministries: ["Media & Tech", "Men's Fellowship"],
    joinDate: "Jun 20, 2021",
    status: "Active",
    gender: "Male",
    address: "8 Cantonments Ave, Accra",
    birthday: "Dec 3, 1995",
    baptismDate: "Sep 12, 2021",
    confirmationDate: "Nov 5, 2022",
    salvationDate: "Jun 20, 2021",
    children: [],
    totalGivingYTD: 3800,
    attendanceRate: 85,
    eventsAttended: 29,
    streak: 6,
    givingHistory: [
      { month: "Jan", tithe: 200, offering: 80, special: 0 },
      { month: "Feb", tithe: 200, offering: 60, special: 0 },
      { month: "Mar", tithe: 250, offering: 80, special: 50 },
      { month: "Apr", tithe: 200, offering: 70, special: 0 },
      { month: "May", tithe: 300, offering: 90, special: 0 },
      { month: "Jun", tithe: 200, offering: 80, special: 0 },
    ],
    serviceAttendance: [
      { label: "Jun 1", attended: true },
      { label: "May 25", attended: false },
      { label: "May 18", attended: true },
      { label: "May 11", attended: true },
      { label: "May 4", attended: true },
      { label: "Apr 27", attended: true },
      { label: "Apr 20", attended: true },
      { label: "Apr 13", attended: false },
      { label: "Apr 6", attended: true },
      { label: "Mar 30", attended: true },
      { label: "Mar 23", attended: false },
      { label: "Mar 16", attended: true },
    ],
    milestones: [
      { type: "birthday", label: "Birthday", date: "Dec 3, 2026", upcoming: true, daysAway: 182 },
      { type: "baptism", label: "Baptism Anniversary", date: "Sep 12, 2026", upcoming: true, daysAway: 100 },
    ],
    notes: [],
  },
  {
    id: "4",
    name: "Akosua Darko",
    initials: "AD",
    avatarColor: "#1A0533",
    phone: "+233 26 321 0987",
    email: "a.darko@email.com",
    ministry: "Prayer Team",
    ministries: ["Prayer Team", "Women's Fellowship"],
    joinDate: "Sep 1, 2018",
    status: "Active",
    gender: "Female",
    address: "22 Tema Road, Tema",
    birthday: "Feb 14, 1985",
    baptismDate: "Dec 25, 2018",
    confirmationDate: "Feb 14, 2019",
    salvationDate: "Sep 1, 2018",
    spouse: "Kwadwo Darko",
    children: ["Esi Darko", "Yaw Darko", "Adwoa Darko"],
    totalGivingYTD: 12000,
    attendanceRate: 96,
    eventsAttended: 52,
    streak: 24,
    givingHistory: [
      { month: "Jan", tithe: 800, offering: 300, special: 200 },
      { month: "Feb", tithe: 800, offering: 250, special: 0 },
      { month: "Mar", tithe: 900, offering: 300, special: 150 },
      { month: "Apr", tithe: 800, offering: 280, special: 0 },
      { month: "May", tithe: 1000, offering: 350, special: 300 },
      { month: "Jun", tithe: 800, offering: 280, special: 0 },
    ],
    serviceAttendance: [
      { label: "Jun 1", attended: true },
      { label: "May 25", attended: true },
      { label: "May 18", attended: true },
      { label: "May 11", attended: true },
      { label: "May 4", attended: true },
      { label: "Apr 27", attended: true },
      { label: "Apr 20", attended: true },
      { label: "Apr 13", attended: true },
      { label: "Apr 6", attended: false },
      { label: "Mar 30", attended: true },
      { label: "Mar 23", attended: true },
      { label: "Mar 16", attended: true },
    ],
    milestones: [
      { type: "wedding", label: "Wedding Anniversary", date: "Jul 20, 2026", upcoming: true, daysAway: 46 },
      { type: "membership", label: "Member Anniversary", date: "Sep 1, 2026", upcoming: true, daysAway: 89 },
      { type: "birthday", label: "Birthday", date: "Feb 14, 2027", upcoming: true, daysAway: 255 },
    ],
    notes: [
      { id: "n4", author: "Pastor Emmanuel", date: "May 30, 2026", content: "Prayer team captain. Spiritually mature, excellent candidate for eldership consideration." },
    ],
  },
  {
    id: "5",
    name: "Samuel Owusu",
    initials: "SO",
    avatarColor: "#7C3AED",
    phone: "+233 50 234 5678",
    email: "s.owusu@email.com",
    ministry: "Evangelism",
    ministries: ["Evangelism", "Men's Fellowship"],
    joinDate: "Apr 12, 2022",
    status: "Active",
    gender: "Male",
    address: "5 Ring Road, Kumasi",
    birthday: "Nov 28, 1993",
    baptismDate: "Jun 20, 2022",
    confirmationDate: "Aug 14, 2023",
    salvationDate: "Apr 12, 2022",
    children: [],
    totalGivingYTD: 4500,
    attendanceRate: 78,
    eventsAttended: 22,
    streak: 4,
    givingHistory: [
      { month: "Jan", tithe: 250, offering: 100, special: 0 },
      { month: "Feb", tithe: 250, offering: 80, special: 0 },
      { month: "Mar", tithe: 300, offering: 100, special: 0 },
      { month: "Apr", tithe: 250, offering: 90, special: 100 },
      { month: "May", tithe: 350, offering: 120, special: 0 },
      { month: "Jun", tithe: 250, offering: 100, special: 0 },
    ],
    serviceAttendance: [
      { label: "Jun 1", attended: true },
      { label: "May 25", attended: true },
      { label: "May 18", attended: false },
      { label: "May 11", attended: false },
      { label: "May 4", attended: true },
      { label: "Apr 27", attended: true },
      { label: "Apr 20", attended: false },
      { label: "Apr 13", attended: true },
      { label: "Apr 6", attended: true },
      { label: "Mar 30", attended: false },
      { label: "Mar 23", attended: false },
      { label: "Mar 16", attended: true },
    ],
    milestones: [
      { type: "baptism", label: "Baptism Anniversary", date: "Jun 20, 2026", upcoming: true, daysAway: 16 },
      { type: "birthday", label: "Birthday", date: "Nov 28, 2026", upcoming: true, daysAway: 177 },
    ],
    notes: [],
  },
  {
    id: "6",
    name: "Gifty Amponsah",
    initials: "GA",
    avatarColor: "#0A7A4A",
    phone: "+233 24 876 5432",
    email: "g.amponsah@email.com",
    ministry: "Children's Ministry",
    ministries: ["Children's Ministry", "Women's Fellowship"],
    joinDate: "Feb 3, 2023",
    status: "Active",
    gender: "Female",
    address: "30 Oxford Street, Osu",
    birthday: "Mar 19, 1997",
    baptismDate: "Apr 9, 2023",
    confirmationDate: "Jun 18, 2024",
    salvationDate: "Feb 3, 2023",
    children: [],
    totalGivingYTD: 2100,
    attendanceRate: 81,
    eventsAttended: 18,
    streak: 5,
    givingHistory: [
      { month: "Jan", tithe: 100, offering: 50, special: 0 },
      { month: "Feb", tithe: 100, offering: 60, special: 0 },
      { month: "Mar", tithe: 150, offering: 50, special: 0 },
      { month: "Apr", tithe: 100, offering: 70, special: 50 },
      { month: "May", tithe: 150, offering: 60, special: 0 },
      { month: "Jun", tithe: 100, offering: 60, special: 0 },
    ],
    serviceAttendance: [
      { label: "Jun 1", attended: true },
      { label: "May 25", attended: true },
      { label: "May 18", attended: true },
      { label: "May 11", attended: false },
      { label: "May 4", attended: true },
      { label: "Apr 27", attended: false },
      { label: "Apr 20", attended: true },
      { label: "Apr 13", attended: true },
      { label: "Apr 6", attended: false },
      { label: "Mar 30", attended: true },
      { label: "Mar 23", attended: true },
      { label: "Mar 16", attended: true },
    ],
    milestones: [
      { type: "birthday", label: "Birthday", date: "Mar 19, 2027", upcoming: true, daysAway: 288 },
      { type: "membership", label: "Member Anniversary", date: "Feb 3, 2027", upcoming: true, daysAway: 244 },
    ],
    notes: [],
  },
  {
    id: "7",
    name: "Nana Ama Yeboah",
    initials: "NY",
    avatarColor: "#1A0533",
    phone: "+233 20 543 2109",
    email: "n.yeboah@email.com",
    ministry: "Welfare",
    ministries: ["Welfare Committee", "Women's Fellowship"],
    joinDate: "Jul 18, 2017",
    status: "Active",
    gender: "Female",
    address: "7 Airport Hills, Accra",
    birthday: "Sep 5, 1982",
    baptismDate: "Sep 10, 2017",
    confirmationDate: "Oct 25, 2018",
    salvationDate: "Jul 18, 2017",
    spouse: "Nana Kweku Yeboah",
    children: ["Akua Yeboah", "Kwesi Yeboah"],
    totalGivingYTD: 9800,
    attendanceRate: 89,
    eventsAttended: 41,
    streak: 10,
    givingHistory: [
      { month: "Jan", tithe: 600, offering: 200, special: 100 },
      { month: "Feb", tithe: 600, offering: 180, special: 0 },
      { month: "Mar", tithe: 700, offering: 200, special: 0 },
      { month: "Apr", tithe: 600, offering: 220, special: 200 },
      { month: "May", tithe: 800, offering: 250, special: 0 },
      { month: "Jun", tithe: 600, offering: 200, special: 0 },
    ],
    serviceAttendance: [
      { label: "Jun 1", attended: true },
      { label: "May 25", attended: true },
      { label: "May 18", attended: true },
      { label: "May 11", attended: true },
      { label: "May 4", attended: true },
      { label: "Apr 27", attended: false },
      { label: "Apr 20", attended: true },
      { label: "Apr 13", attended: true },
      { label: "Apr 6", attended: true },
      { label: "Mar 30", attended: true },
      { label: "Mar 23", attended: true },
      { label: "Mar 16", attended: false },
    ],
    milestones: [
      { type: "membership", label: "Member Anniversary", date: "Jul 18, 2026", upcoming: true, daysAway: 44 },
      { type: "birthday", label: "Birthday", date: "Sep 5, 2026", upcoming: true, daysAway: 93 },
      { type: "wedding", label: "Wedding Anniversary", date: "Dec 12, 2026", upcoming: true, daysAway: 191 },
    ],
    notes: [],
  },
  {
    id: "8",
    name: "Prince Amoah",
    initials: "PA",
    avatarColor: "#0A4A3A",
    phone: "+233 27 654 3210",
    email: "p.amoah@email.com",
    ministry: "Youth",
    ministries: ["Youth Ministry", "Choir"],
    joinDate: "Nov 5, 2024",
    status: "Active",
    gender: "Male",
    address: "15 Spintex Road, Accra",
    birthday: "Jan 7, 2002",
    baptismDate: "Jan 5, 2025",
    confirmationDate: "",
    salvationDate: "Nov 5, 2024",
    children: [],
    totalGivingYTD: 1200,
    attendanceRate: 75,
    eventsAttended: 14,
    streak: 3,
    givingHistory: [
      { month: "Jan", tithe: 50, offering: 30, special: 0 },
      { month: "Feb", tithe: 50, offering: 20, special: 0 },
      { month: "Mar", tithe: 80, offering: 30, special: 0 },
      { month: "Apr", tithe: 50, offering: 25, special: 0 },
      { month: "May", tithe: 100, offering: 40, special: 0 },
      { month: "Jun", tithe: 50, offering: 30, special: 0 },
    ],
    serviceAttendance: [
      { label: "Jun 1", attended: true },
      { label: "May 25", attended: true },
      { label: "May 18", attended: true },
      { label: "May 11", attended: false },
      { label: "May 4", attended: false },
      { label: "Apr 27", attended: true },
      { label: "Apr 20", attended: false },
      { label: "Apr 13", attended: true },
      { label: "Apr 6", attended: true },
      { label: "Mar 30", attended: false },
      { label: "Mar 23", attended: false },
      { label: "Mar 16", attended: true },
    ],
    milestones: [
      { type: "birthday", label: "Birthday", date: "Jan 7, 2027", upcoming: true, daysAway: 217 },
    ],
    notes: [],
  },
  {
    id: "9",
    name: "Kwabena Osei",
    initials: "KO",
    avatarColor: "#C8860A",
    phone: "+233 24 109 8765",
    email: "k.osei@email.com",
    ministry: "Ushering",
    ministries: ["Ushering"],
    joinDate: "May 28, 2026",
    status: "First-timer",
    gender: "Male",
    address: "18 Dansoman, Accra",
    birthday: "Apr 20, 1999",
    baptismDate: "",
    confirmationDate: "",
    salvationDate: "May 28, 2026",
    children: [],
    totalGivingYTD: 150,
    attendanceRate: 60,
    eventsAttended: 3,
    streak: 1,
    givingHistory: [
      { month: "Jan", tithe: 0, offering: 0, special: 0 },
      { month: "Feb", tithe: 0, offering: 0, special: 0 },
      { month: "Mar", tithe: 0, offering: 0, special: 0 },
      { month: "Apr", tithe: 0, offering: 0, special: 0 },
      { month: "May", tithe: 0, offering: 50, special: 0 },
      { month: "Jun", tithe: 0, offering: 100, special: 0 },
    ],
    serviceAttendance: [
      { label: "Jun 1", attended: true },
      { label: "May 25", attended: false },
      { label: "May 18", attended: false },
      { label: "May 11", attended: false },
      { label: "May 4", attended: false },
      { label: "Apr 27", attended: false },
      { label: "Apr 20", attended: false },
      { label: "Apr 13", attended: false },
      { label: "Apr 6", attended: false },
      { label: "Mar 30", attended: false },
      { label: "Mar 23", attended: false },
      { label: "Mar 16", attended: false },
    ],
    milestones: [
      { type: "birthday", label: "Birthday", date: "Apr 20, 2027", upcoming: true, daysAway: 320 },
    ],
    notes: [
      { id: "n5", author: "Admin", date: "May 28, 2026", content: "First-time visitor. Referred by Emmanuel Asante. Follow up for membership class invitation." },
    ],
  },
  {
    id: "10",
    name: "Yaw Mensah-Bonsu",
    initials: "YM",
    avatarColor: "#2D1B69",
    phone: "+233 20 334 5566",
    email: "y.mensah@email.com",
    ministry: "Media & Tech",
    ministries: ["Media & Tech"],
    joinDate: "Aug 10, 2020",
    status: "Inactive",
    gender: "Male",
    address: "24 Madina Road, Accra",
    birthday: "Oct 30, 1991",
    baptismDate: "Oct 18, 2020",
    confirmationDate: "",
    salvationDate: "Aug 10, 2020",
    children: [],
    totalGivingYTD: 800,
    attendanceRate: 35,
    eventsAttended: 5,
    streak: 0,
    givingHistory: [
      { month: "Jan", tithe: 0, offering: 50, special: 0 },
      { month: "Feb", tithe: 0, offering: 0, special: 0 },
      { month: "Mar", tithe: 100, offering: 50, special: 0 },
      { month: "Apr", tithe: 0, offering: 0, special: 0 },
      { month: "May", tithe: 0, offering: 50, special: 0 },
      { month: "Jun", tithe: 0, offering: 0, special: 0 },
    ],
    serviceAttendance: [
      { label: "Jun 1", attended: false },
      { label: "May 25", attended: false },
      { label: "May 18", attended: false },
      { label: "May 11", attended: true },
      { label: "May 4", attended: false },
      { label: "Apr 27", attended: false },
      { label: "Apr 20", attended: true },
      { label: "Apr 13", attended: false },
      { label: "Apr 6", attended: false },
      { label: "Mar 30", attended: false },
      { label: "Mar 23", attended: true },
      { label: "Mar 16", attended: false },
    ],
    milestones: [
      { type: "birthday", label: "Birthday", date: "Oct 30, 2026", upcoming: true, daysAway: 148 },
    ],
    notes: [
      { id: "n6", author: "Admin", date: "Apr 1, 2026", content: "Inactive for 3 months. Needs pastoral follow-up and re-engagement outreach." },
    ],
  },
  {
    id: "11",
    name: "Adwoa Frimpong",
    initials: "AF",
    avatarColor: "#0A4A3A",
    phone: "+233 26 789 0123",
    email: "a.frimpong@email.com",
    ministry: "Choir",
    ministries: ["Choir", "Women's Fellowship"],
    joinDate: "May 31, 2026",
    status: "First-timer",
    gender: "Female",
    address: "3 East Legon, Accra",
    birthday: "Jul 11, 2001",
    baptismDate: "",
    confirmationDate: "",
    salvationDate: "May 31, 2026",
    children: [],
    totalGivingYTD: 100,
    attendanceRate: 40,
    eventsAttended: 2,
    streak: 0,
    givingHistory: [
      { month: "Jan", tithe: 0, offering: 0, special: 0 },
      { month: "Feb", tithe: 0, offering: 0, special: 0 },
      { month: "Mar", tithe: 0, offering: 0, special: 0 },
      { month: "Apr", tithe: 0, offering: 0, special: 0 },
      { month: "May", tithe: 0, offering: 50, special: 0 },
      { month: "Jun", tithe: 0, offering: 50, special: 0 },
    ],
    serviceAttendance: [
      { label: "Jun 1", attended: true },
      { label: "May 25", attended: false },
      { label: "May 18", attended: false },
      { label: "May 11", attended: false },
      { label: "May 4", attended: false },
      { label: "Apr 27", attended: false },
      { label: "Apr 20", attended: false },
      { label: "Apr 13", attended: false },
      { label: "Apr 6", attended: false },
      { label: "Mar 30", attended: false },
      { label: "Mar 23", attended: false },
      { label: "Mar 16", attended: false },
    ],
    milestones: [
      { type: "birthday", label: "Birthday", date: "Jul 11, 2026", upcoming: true, daysAway: 37 },
    ],
    notes: [],
  },
  {
    id: "12",
    name: "Efua Asante",
    initials: "EA",
    avatarColor: "#C8860A",
    phone: "+233 27 221 3344",
    email: "efua.asante@email.com",
    ministry: "Evangelism",
    ministries: ["Evangelism", "Prayer Team"],
    joinDate: "Mar 14, 2022",
    status: "Active",
    gender: "Female",
    address: "11 Tesano, Accra",
    birthday: "Dec 25, 1994",
    baptismDate: "May 1, 2022",
    confirmationDate: "Jul 4, 2023",
    salvationDate: "Mar 14, 2022",
    spouse: "Kojo Asante",
    children: ["Baby Asante"],
    totalGivingYTD: 6200,
    attendanceRate: 90,
    eventsAttended: 35,
    streak: 14,
    givingHistory: [
      { month: "Jan", tithe: 350, offering: 120, special: 0 },
      { month: "Feb", tithe: 350, offering: 100, special: 0 },
      { month: "Mar", tithe: 400, offering: 130, special: 100 },
      { month: "Apr", tithe: 350, offering: 120, special: 0 },
      { month: "May", tithe: 500, offering: 150, special: 200 },
      { month: "Jun", tithe: 350, offering: 120, special: 0 },
    ],
    serviceAttendance: [
      { label: "Jun 1", attended: true },
      { label: "May 25", attended: true },
      { label: "May 18", attended: true },
      { label: "May 11", attended: true },
      { label: "May 4", attended: true },
      { label: "Apr 27", attended: true },
      { label: "Apr 20", attended: true },
      { label: "Apr 13", attended: true },
      { label: "Apr 6", attended: true },
      { label: "Mar 30", attended: true },
      { label: "Mar 23", attended: true },
      { label: "Mar 16", attended: false },
    ],
    milestones: [
      { type: "wedding", label: "Wedding Anniversary", date: "Aug 14, 2026", upcoming: true, daysAway: 71 },
      { type: "birthday", label: "Birthday", date: "Dec 25, 2026", upcoming: true, daysAway: 204 },
    ],
    notes: [],
  },
];
